# -*- coding: utf-8 -*-
"""Person Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GnkfTPd-XD_oh-2cOUzkUrpl5oYRxvNc
"""

# Commented out IPython magic to ensure Python compatibility.
#clone YOLOv5 and
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt # install dependencies
# %pip install -q roboflow

import torch
import os
from IPython.display import Image, clear_output  # to display images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

!unzip /content/PersonDection.v5i.yolov5pytorch.zip -d /content/yolov5

!python /content/yolov5/train.py --img 256 --batch 16 --epochs 25 --data /content/yolov5/data.yaml --weights yolov5s.pt --cache

!python /content/yolov5/detect.py --weights runs/train/exp/weights/best.pt --img 256 --conf 0.20 --source /content/yolov5/test/images

import glob
from PIL import Image
from IPython.display import display
for imageName in glob.glob('/content/yolov5/runs/detect/exp/*.jpg'):
    img = Image.open(imageName)
    display(img)